/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ping": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Ping */
    get: operations["ping_ping_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/domains": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Domains */
    get: operations["list_domains_domains_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/domains/{domain}/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Reports */
    get: operations["list_reports_domains__domain__reports_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/domains/{domain}/reports/{report_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Report */
    get: operations["get_report_domains__domain__reports__report_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/domains/{domain}/reports/{report_id}/records": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Records */
    get: operations["list_records_domains__domain__reports__report_id__records_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AuthResult */
    AuthResult: {
      /**
       * Type
       * @enum {string}
       */
      type: "dkim" | "spf"
      /**
       * Result
       * @enum {string}
       */
      result:
        | "pass"
        | "fail"
        | "softfail"
        | "neutral"
        | "none"
        | "temperror"
        | "permerror"
      /** Domain */
      domain: string
    }
    /** DomainsResponse */
    DomainsResponse: {
      /** Domains */
      domains: string[]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** PingResponse */
    PingResponse: {
      /** Message */
      message: string
    }
    /** Record */
    Record: {
      /** Source Ip */
      source_ip: string
      /** Count */
      count: number
      /**
       * Disposition
       * @enum {string}
       */
      disposition: "none" | "quarantine" | "reject"
      /**
       * Dkim Aligned
       * @enum {string}
       */
      dkim_aligned: "pass" | "fail"
      /**
       * Spf Aligned
       * @enum {string}
       */
      spf_aligned: "pass" | "fail"
      /** Header From */
      header_from: string
      /** Auth Results */
      auth_results: components["schemas"]["AuthResult"][]
    }
    /** RecordsResponse */
    RecordsResponse: {
      /** Items */
      items: components["schemas"]["Record"][]
    }
    /** Report */
    Report: {
      /** Report Id */
      report_id: string
      /** Org Name */
      org_name: string
      /** Org Email */
      org_email: string
      /** Begin Date */
      begin_date: number
      /** End Date */
      end_date: number
      /**
       * Policy
       * @enum {string}
       */
      policy: "reject" | "quarantine" | "none"
      /**
       * Adkim
       * @enum {string}
       */
      adkim: "r" | "s"
      /**
       * Aspf
       * @enum {string}
       */
      aspf: "r" | "s"
      /** Subdomain Policy */
      subdomain_policy?: ("reject" | "quarantine" | "none") | null
      /** Pct */
      pct: number
    }
    /** ReportsResponse */
    ReportsResponse: {
      /** Items */
      items: components["schemas"]["Report"][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  ping_ping_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PingResponse"]
        }
      }
    }
  }
  list_domains_domains_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["DomainsResponse"]
        }
      }
    }
  }
  list_reports_domains__domain__reports_get: {
    parameters: {
      query?: {
        from?: number | null
        to?: number | null
        limit?: number
        cursor?: string | null
      }
      header?: never
      path: {
        domain: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportsResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_report_domains__domain__reports__report_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        domain: string
        report_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Report"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_records_domains__domain__reports__report_id__records_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        domain: string
        report_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RecordsResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
}
